import { PromotionModel } from "@/types/commonType";
import {
  ePromotion,
  eScene,
  eTerrainType,
  eUnitType,
} from "@/staticData/enums";

export const promotionArray: Array<PromotionModel> = [
  {
    id: ePromotion.PROMOTION_GREAT_GENENAL,
    name: "大军",
    scene: eScene.SCENE_ALL,
    selfUnitType: eUnitType.UNIT_TYPE_ALL,
    selfTerrainType: eTerrainType.TERRAIN_ALL,
    selfModify: 15,
    targetUnitType: [],
    targetTerrainType: eTerrainType.TERRAIN_ALL,
    targetModify: 0,
    barbarainOnly: false,
    description: "相邻单位战斗力+15%",
    uuid: [],
    iconName: "UNIT_GREAT_GENERAL.png",
  },
  {
    id: ePromotion.PROMOTION_CITADEL,
    name: "军事要塞",
    scene: eScene.SCENE_DEF,
    selfUnitType: eUnitType.UNIT_TYPE_ALL,
    selfTerrainType: eTerrainType.TERRAIN_ALL,
    selfModify: 100,
    targetTerrainType: eUnitType.UNIT_TYPE_ALL,
    targetUnitType: [],
    targetModify: 0,
    barbarainOnly: false,
    description: "防御时战斗力+100%",
    uuid: [],
    iconName: "IMPROVEMENT_CITADEL.png",
  },
  {
    id: ePromotion.PROMOTION_GARRISON,
    name: "驻防",
    scene: eScene.SCENE_DEF,
    selfUnitType: eUnitType.UNIT_TYPE_CLOSECOMBAT,
    selfTerrainType: eTerrainType.TERRAIN_ALL,
    selfModify: 40,
    targetTerrainType: eUnitType.UNIT_TYPE_ALL,
    targetUnitType: [],
    targetModify: 0,
    barbarainOnly: false,
    description: "驻防时战斗力+40%",
    uuid: [],
    iconName: "BUILDING_ARMORY.png",
  },
  {
    id: ePromotion.PROMOTION_PINCER,
    name: "夹击",
    scene: eScene.SCENE_ATK,
    selfUnitType: eUnitType.UNIT_TYPE_ALL,
    selfTerrainType: eTerrainType.TERRAIN_ALL,
    selfModify: 10,
    targetTerrainType: eUnitType.UNIT_TYPE_ALL,
    targetUnitType: [],
    targetModify: 0,
    barbarainOnly: false,
    description: "夹击时战斗力+10%",
    uuid: [],
    iconName: "POLICY_PROFESSIONAL_ARMY.png",
  },
  {
    id: ePromotion.PROMOTION_HONOR,
    name: "荣誉开门",
    scene: eScene.SCENE_ALL,
    selfUnitType: eUnitType.UNIT_TYPE_ALL,
    selfTerrainType: eTerrainType.TERRAIN_ALL,
    selfModify: 33,
    targetUnitType: [],
    targetTerrainType: eTerrainType.TERRAIN_ALL,
    targetModify: 0,
    barbarainOnly: true,
    description: "对蛮族单位战斗力+33%",
    uuid: [],
    iconName: "POLICY_NEW_ORDER.png",
  },
  {
    id: ePromotion.PROMOTION_HONOR_DISCIPLINE,
    name: "军事纪律",
    scene: eScene.SCENE_ALL,
    selfUnitType: eUnitType.UNIT_TYPE_CLOSECOMBAT,
    selfTerrainType: eTerrainType.TERRAIN_ALL,
    selfModify: 33,
    targetUnitType: [],
    targetTerrainType: eTerrainType.TERRAIN_ALL,
    targetModify: 0,
    barbarainOnly: false,
    description: "有相邻友方单位时战斗力+15%",
    uuid: [],
    iconName: "POLICY_DISCIPLINE.png",
  },
  {
    id: ePromotion.PROMOTION_EMBATTLE_I,
    name: "列阵一级",
    scene: eScene.SCENE_ALL,
    selfUnitType: eUnitType.UNIT_TYPE_CLOSECOMBAT,
    selfTerrainType: eTerrainType.TERRAIN_ALL,
    selfModify: 33,
    targetUnitType: [eUnitType.UNIT_TYPE_RIDING],
    targetTerrainType: eTerrainType.TERRAIN_ALL,
    targetModify: 0,
    barbarainOnly: false,
    description: "与骑乘单位战斗时战斗力+33%",
    uuid: [],
    iconName: "PROMOTION_PROMOTION_ATLAS24.png",
  },
  {
    id: ePromotion.PROMOTION_EMBATTLE_II,
    name: "列阵二级",
    scene: eScene.SCENE_ALL,
    selfUnitType: eUnitType.UNIT_TYPE_CLOSECOMBAT,
    selfTerrainType: eTerrainType.TERRAIN_ALL,
    selfModify: 33,
    targetUnitType: [eUnitType.UNIT_TYPE_RIDING],
    targetTerrainType: eTerrainType.TERRAIN_ALL,
    targetModify: 0,
    barbarainOnly: false,
    description: "与骑乘单位战斗时战斗力+33%",
    uuid: [],
    iconName: "PROMOTION_PROMOTION_ATLAS25.png",
  },
];
