import { eEra, eTechnology } from "@/staticData/enums";
import { TechnologyModel } from "@/types/commonType";

//实际科研需求计算公式：science = base * cost * (1 + punishment * citynumber)
//cost：较小及以下，标准，较大，极大分别为1,1.1,1.2,1.3
//punishment:标准及以下，较大，极大:5,3.75,2.5
//eg:基础值为780的声学，在标准图上的科研需求按城市数从1到8分别为：780 * 1.1 * (1 + 0.05*(1~8)) = 900.9(901)/943.8(944)...

export const technologiesArray: Array<TechnologyModel> = [
  /*ancient */
  {
    id: eTechnology.TECH_AGRICULTURE,
    name: "农业",
    era: eEra.ERA_ANCIENT,
    cost: 20,
    preTechList: [],
  },
  {
    id: eTechnology.TECH_POTTERY,
    name: "制陶",
    era: eEra.ERA_ANCIENT,
    cost: 35,
    preTechList: [eTechnology.TECH_AGRICULTURE],
  },
  {
    id: eTechnology.TECH_ANIMAL_HUSBANDRY,
    name: "畜牧",
    era: eEra.ERA_ANCIENT,
    cost: 35,
    preTechList: [eTechnology.TECH_AGRICULTURE],
  },
  {
    id: eTechnology.TECH_ARCHERY,
    name: "弓箭",
    era: eEra.ERA_ANCIENT,
    cost: 35,
    preTechList: [eTechnology.TECH_AGRICULTURE],
  },
  {
    id: eTechnology.TECH_MINING,
    name: "采矿",
    era: eEra.ERA_ANCIENT,
    cost: 35,
    preTechList: [eTechnology.TECH_AGRICULTURE],
  },
  {
    id: eTechnology.TECH_SAILING,
    name: "航海",
    era: eEra.ERA_ANCIENT,
    cost: 55,
    preTechList: [eTechnology.TECH_POTTERY],
  },
  {
    id: eTechnology.TECH_CALENDAR,
    name: "历法",
    era: eEra.ERA_ANCIENT,
    cost: 55,
    preTechList: [eTechnology.TECH_POTTERY],
  },
  {
    id: eTechnology.TECH_WRITING,
    name: "书写",
    era: eEra.ERA_ANCIENT,
    cost: 55,
    preTechList: [eTechnology.TECH_POTTERY],
  },
  {
    id: eTechnology.TECH_TRAPPING,
    name: "捕猎",
    era: eEra.ERA_ANCIENT,
    cost: 55,
    preTechList: [eTechnology.TECH_ANIMAL_HUSBANDRY],
  },
  {
    id: eTechnology.TECH_THE_WHEEL,
    name: "车轮",
    era: eEra.ERA_ANCIENT,
    cost: 55,
    preTechList: [eTechnology.TECH_ANIMAL_HUSBANDRY, eTechnology.TECH_ARCHERY],
  },
  {
    id: eTechnology.TECH_MASONRY,
    name: "石工",
    era: eEra.ERA_ANCIENT,
    cost: 55,
    preTechList: [eTechnology.TECH_MINING],
  },
  {
    id: eTechnology.TECH_BRONZE_WORKING,
    name: "青铜",
    era: eEra.ERA_ANCIENT,
    cost: 55,
    preTechList: [eTechnology.TECH_MINING],
  },

  /*classical */
  {
    id: eTechnology.TECH_OPTICS,
    name: "光学",
    era: eEra.ERA_CLASSICAL,
    cost: 85,
    preTechList: [eTechnology.TECH_SAILING],
  },
  {
    id: eTechnology.TECH_HORSEBACK_RIDING,
    name: "骑术",
    era: eEra.ERA_CLASSICAL,
    cost: 105,
    preTechList: [eTechnology.TECH_TRAPPING, eTechnology.TECH_THE_WHEEL],
  },
  {
    id: eTechnology.TECH_MATHEMATICS,
    name: "数学",
    era: eEra.ERA_CLASSICAL,
    cost: 105,
    preTechList: [eTechnology.TECH_THE_WHEEL],
  },
  {
    id: eTechnology.TECH_CONSTRUCTION,
    name: "建造学",
    era: eEra.ERA_CLASSICAL,
    cost: 105,
    preTechList: [eTechnology.TECH_THE_WHEEL, eTechnology.TECH_MASONRY],
  },
  {
    id: eTechnology.TECH_PHILOSOPHY,
    name: "哲学",
    era: eEra.ERA_CLASSICAL,
    cost: 175,
    preTechList: [eTechnology.TECH_CALENDAR, eTechnology.TECH_WRITING],
  },
  {
    id: eTechnology.TECH_DRAMA,
    name: "戏剧",
    era: eEra.ERA_CLASSICAL,
    cost: 175,
    preTechList: [eTechnology.TECH_WRITING],
  },
  {
    id: eTechnology.TECH_CURRENCY,
    name: "货币",
    era: eEra.ERA_CLASSICAL,
    cost: 175,
    preTechList: [eTechnology.TECH_MATHEMATICS],
  },
  {
    id: eTechnology.TECH_ENGINEERING,
    name: "工程学",
    era: eEra.ERA_CLASSICAL,
    cost: 175,
    preTechList: [eTechnology.TECH_MATHEMATICS, eTechnology.TECH_CONSTRUCTION],
  },
  {
    id: eTechnology.TECH_IRON_WORKING,
    name: "铁器",
    era: eEra.ERA_CLASSICAL,
    cost: 175,
    preTechList: [eTechnology.TECH_BRONZE_WORKING],
  },

  /*medieval */
  {
    id: eTechnology.TECH_THEOLOGY,
    name: "神学",
    era: eEra.ERA_MEDIEVAL,
    cost: 275,
    preTechList: [eTechnology.TECH_PHILOSOPHY, eTechnology.TECH_DRAMA],
  },
  {
    id: eTechnology.TECH_CIVIL_SERVICE,
    name: "文官",
    era: eEra.ERA_MEDIEVAL,
    cost: 275,
    preTechList: [
      eTechnology.TECH_DRAMA,
      eTechnology.TECH_HORSEBACK_RIDING,
      eTechnology.TECH_CURRENCY,
    ],
  },
  {
    id: eTechnology.TECH_GUILDS,
    name: "行会",
    era: eEra.ERA_MEDIEVAL,
    cost: 275,
    preTechList: [eTechnology.TECH_CURRENCY],
  },
  {
    id: eTechnology.TECH_METAL_CASTING,
    name: "铸造",
    era: eEra.ERA_MEDIEVAL,
    cost: 275,
    preTechList: [eTechnology.TECH_ENGINEERING, eTechnology.TECH_IRON_WORKING],
  },
  {
    id: eTechnology.TECH_COMPASS,
    name: "罗盘",
    era: eEra.ERA_MEDIEVAL,
    cost: 375,
    preTechList: [eTechnology.TECH_OPTICS],
  },
  {
    id: eTechnology.TECH_EDUCATION,
    name: "教育",
    era: eEra.ERA_MEDIEVAL,
    cost: 485,
    preTechList: [eTechnology.TECH_THEOLOGY, eTechnology.TECH_CIVIL_SERVICE],
  },
  {
    id: eTechnology.TECH_CHIVALRY,
    name: "骑士",
    era: eEra.ERA_MEDIEVAL,
    cost: 485,
    preTechList: [eTechnology.TECH_GUILDS, eTechnology.TECH_CIVIL_SERVICE],
  },
  {
    id: eTechnology.TECH_MACHINERY,
    name: "机械",
    era: eEra.ERA_MEDIEVAL,
    cost: 485,
    preTechList: [eTechnology.TECH_GUILDS, eTechnology.TECH_ENGINEERING],
  },
  {
    id: eTechnology.TECH_PHYSICS,
    name: "物理学",
    era: eEra.ERA_MEDIEVAL,
    cost: 485,
    preTechList: [eTechnology.TECH_METAL_CASTING],
  },
  {
    id: eTechnology.TECH_STEEL,
    name: "炼钢",
    era: eEra.ERA_MEDIEVAL,
    cost: 485,
    preTechList: [eTechnology.TECH_METAL_CASTING],
  },

  /*renaissance*/
  {
    id: eTechnology.TECH_ASTRONOMY,
    name: "天文学",
    era: eEra.ERA_RENAISSANCE,
    cost: 780,
    preTechList: [eTechnology.TECH_COMPASS, eTechnology.TECH_EDUCATION],
  },
  {
    id: eTechnology.TECH_ACOUSTICS,
    name: "声学",
    era: eEra.ERA_RENAISSANCE,
    cost: 780,
    preTechList: [eTechnology.TECH_EDUCATION],
  },
  {
    id: eTechnology.TECH_BANKING,
    name: "银行",
    era: eEra.ERA_RENAISSANCE,
    cost: 780,
    preTechList: [eTechnology.TECH_EDUCATION, eTechnology.TECH_CHIVALRY],
  },
  {
    id: eTechnology.TECH_PRINTING_PRESS,
    name: "印刷",
    era: eEra.ERA_RENAISSANCE,
    cost: 780,
    preTechList: [
      eTechnology.TECH_CHIVALRY,
      eTechnology.TECH_MACHINERY,
      eTechnology.TECH_PHYSICS,
    ],
  },
  {
    id: eTechnology.TECH_GUNPOWDER,
    name: "火药",
    era: eEra.ERA_RENAISSANCE,
    cost: 780,
    preTechList: [eTechnology.TECH_PHYSICS, eTechnology.TECH_STEEL],
  },
  {
    id: eTechnology.TECH_NAVIGATION,
    name: "导航",
    era: eEra.ERA_RENAISSANCE,
    cost: 1150,
    preTechList: [eTechnology.TECH_ASTRONOMY],
  },
  {
    id: eTechnology.TECH_ARCHITECTURE,
    name: "建筑学",
    era: eEra.ERA_RENAISSANCE,
    cost: 1150,
    preTechList: [eTechnology.TECH_ACOUSTICS, eTechnology.TECH_BANKING],
  },
  {
    id: eTechnology.TECH_ECONOMICS,
    name: "经济学",
    era: eEra.ERA_RENAISSANCE,
    cost: 1150,
    preTechList: [eTechnology.TECH_PRINTING_PRESS, eTechnology.TECH_BANKING],
  },
  {
    id: eTechnology.TECH_METALLURGY,
    name: "冶金",
    era: eEra.ERA_RENAISSANCE,
    cost: 1150,
    preTechList: [eTechnology.TECH_PRINTING_PRESS, eTechnology.TECH_GUNPOWDER],
  },
  {
    id: eTechnology.TECH_CHEMISTRY,
    name: "化学",
    era: eEra.ERA_RENAISSANCE,
    cost: 1150,
    preTechList: [eTechnology.TECH_GUNPOWDER],
  },

  /*industrial*/
  {
    id: eTechnology.TECH_ARCHAEOLOGY,
    name: "考古学",
    era: eEra.ERA_INDUSTRIAL,
    cost: 1600,
    preTechList: [eTechnology.TECH_NAVIGATION, eTechnology.TECH_ARCHITECTURE],
  },
  {
    id: eTechnology.TECH_SCIENTIFIC_THEORY,
    name: "科学理论",
    era: eEra.ERA_INDUSTRIAL,
    cost: 1600,
    preTechList: [eTechnology.TECH_ARCHITECTURE, eTechnology.TECH_ECONOMICS],
  },
  {
    id: eTechnology.TECH_INDUSTRIALIZATION,
    name: "工业化",
    era: eEra.ERA_INDUSTRIAL,
    cost: 1600,
    preTechList: [eTechnology.TECH_ECONOMICS],
  },
  {
    id: eTechnology.TECH_RIFLING,
    name: "膛线",
    era: eEra.ERA_INDUSTRIAL,
    cost: 1600,
    preTechList: [eTechnology.TECH_ECONOMICS, eTechnology.TECH_METALLURGY],
  },
  {
    id: eTechnology.TECH_MILITARY_SCIENCE,
    name: "军事科学",
    era: eEra.ERA_INDUSTRIAL,
    cost: 1600,
    preTechList: [eTechnology.TECH_CHEMISTRY, eTechnology.TECH_METALLURGY],
  },
  {
    id: eTechnology.TECH_FERTILIZER,
    name: "化肥",
    era: eEra.ERA_INDUSTRIAL,
    cost: 1600,
    preTechList: [eTechnology.TECH_CHEMISTRY],
  },
  {
    id: eTechnology.TECH_BIOLOGY,
    name: "生物学",
    era: eEra.ERA_INDUSTRIAL,
    cost: 2350,
    preTechList: [
      eTechnology.TECH_ARCHAEOLOGY,
      eTechnology.TECH_SCIENTIFIC_THEORY,
    ],
  },
  {
    id: eTechnology.TECH_ELECTRICITY,
    name: "电力",
    era: eEra.ERA_INDUSTRIAL,
    cost: 2350,
    preTechList: [eTechnology.TECH_SCIENTIFIC_THEORY],
  },
  {
    id: eTechnology.TECH_STEAM_POWER,
    name: "蒸汽动力",
    era: eEra.ERA_INDUSTRIAL,
    cost: 2350,
    preTechList: [
      eTechnology.TECH_SCIENTIFIC_THEORY,
      eTechnology.TECH_INDUSTRIALIZATION,
      eTechnology.TECH_RIFLING,
    ],
  },
  {
    id: eTechnology.TECH_DYNAMITE,
    name: "炸药",
    era: eEra.ERA_INDUSTRIAL,
    cost: 2350,
    preTechList: [
      eTechnology.TECH_MILITARY_SCIENCE,
      eTechnology.TECH_FERTILIZER,
    ],
  },

  /*modern*/
  {
    id: eTechnology.TECH_REFRIGERATION,
    name: "制冷",
    era: eEra.ERA_MODERN,
    cost: 3100,
    preTechList: [eTechnology.TECH_BIOLOGY, eTechnology.TECH_ELECTRICITY],
  },
  {
    id: eTechnology.TECH_RADIO,
    name: "无线电",
    era: eEra.ERA_MODERN,
    cost: 3100,
    preTechList: [eTechnology.TECH_ELECTRICITY],
  },
  {
    id: eTechnology.TECH_REPLACEABLE_PARTS,
    name: "零组件",
    era: eEra.ERA_MODERN,
    cost: 3100,
    preTechList: [eTechnology.TECH_ELECTRICITY, eTechnology.TECH_STEAM_POWER],
  },
  {
    id: eTechnology.TECH_FLIGHT,
    name: "航空",
    era: eEra.ERA_MODERN,
    cost: 3100,
    preTechList: [eTechnology.TECH_STEAM_POWER],
  },
  {
    id: eTechnology.TECH_RAILROAD,
    name: "铁路",
    era: eEra.ERA_MODERN,
    cost: 3100,
    preTechList: [eTechnology.TECH_STEAM_POWER, eTechnology.TECH_DYNAMITE],
  },
  {
    id: eTechnology.TECH_PLASTIC,
    name: "塑料",
    era: eEra.ERA_MODERN,
    cost: 4100,
    preTechList: [eTechnology.TECH_RADIO, eTechnology.TECH_REPLACEABLE_PARTS],
  },
  {
    id: eTechnology.TECH_ELECTRONICS,
    name: "电子学",
    era: eEra.ERA_MODERN,
    cost: 4100,
    preTechList: [eTechnology.TECH_FLIGHT, eTechnology.TECH_REPLACEABLE_PARTS],
  },
  {
    id: eTechnology.TECH_BALLISTICS,
    name: "弹道学",
    era: eEra.ERA_MODERN,
    cost: 4100,
    preTechList: [eTechnology.TECH_FLIGHT, eTechnology.TECH_RAILROAD],
  },
  {
    id: eTechnology.TECH_COMBUSTION,
    name: "内燃机",
    era: eEra.ERA_MODERN,
    cost: 4100,
    preTechList: [eTechnology.TECH_RAILROAD],
  },

  /*atomic*/
  {
    id: eTechnology.TECH_PENICILIN,
    name: "青霉素",
    era: eEra.ERA_ATOMIC,
    cost: 5100,
    preTechList: [eTechnology.TECH_PLASTIC, eTechnology.TECH_REFRIGERATION],
  },
  {
    id: eTechnology.TECH_ATOMIC_THEORY,
    name: "原子理论",
    era: eEra.ERA_ATOMIC,
    cost: 5100,
    preTechList: [eTechnology.TECH_PLASTIC, eTechnology.TECH_ELECTRONICS],
  },
  {
    id: eTechnology.TECH_RADAR,
    name: "雷达",
    era: eEra.ERA_ATOMIC,
    cost: 5100,
    preTechList: [eTechnology.TECH_BALLISTICS, eTechnology.TECH_ELECTRONICS],
  },
  {
    id: eTechnology.TECH_COMBINED_ARMS,
    name: "联合兵种",
    era: eEra.ERA_ATOMIC,
    cost: 5100,
    preTechList: [eTechnology.TECH_BALLISTICS, eTechnology.TECH_COMBUSTION],
  },
  {
    id: eTechnology.TECH_ECOLOGY,
    name: "生态学",
    era: eEra.ERA_ATOMIC,
    cost: 6400,
    preTechList: [eTechnology.TECH_PENICILIN, eTechnology.TECH_ATOMIC_THEORY],
  },
  {
    id: eTechnology.TECH_NUCLEAR_FISSION,
    name: "核裂变",
    era: eEra.ERA_ATOMIC,
    cost: 6400,
    preTechList: [eTechnology.TECH_RADAR, eTechnology.TECH_ATOMIC_THEORY],
  },
  {
    id: eTechnology.TECH_ROCKETRY,
    name: "火箭学",
    era: eEra.ERA_ATOMIC,
    cost: 6400,
    preTechList: [eTechnology.TECH_RADAR, eTechnology.TECH_ATOMIC_THEORY],
  },
  {
    id: eTechnology.TECH_COMPUTERS,
    name: "计算机",
    era: eEra.ERA_ATOMIC,
    cost: 6400,
    preTechList: [eTechnology.TECH_RADAR, eTechnology.TECH_COMBINED_ARMS],
  },

  /*infomation*/
  {
    id: eTechnology.TECH_TELECOM,
    name: "电信科技",
    era: eEra.ERA_INFOMATION,
    cost: 7700,
    preTechList: [eTechnology.TECH_ECOLOGY],
  },
  {
    id: eTechnology.TECH_MOBILE_TACTICS,
    name: "机动战术",
    era: eEra.ERA_INFOMATION,
    cost: 7700,
    preTechList: [eTechnology.TECH_ECOLOGY, eTechnology.TECH_NUCLEAR_FISSION],
  },
  {
    id: eTechnology.TECH_ADVANCED_BALLISTICS,
    name: "高级弹道学",
    era: eEra.ERA_INFOMATION,
    cost: 7700,
    preTechList: [eTechnology.TECH_ROCKETRY, eTechnology.TECH_NUCLEAR_FISSION],
  },
  {
    id: eTechnology.TECH_SATELLITES,
    name: "卫星",
    era: eEra.ERA_INFOMATION,
    cost: 7700,
    preTechList: [eTechnology.TECH_ROCKETRY],
  },
  {
    id: eTechnology.TECH_ROBOTICS,
    name: "机器人学",
    era: eEra.ERA_INFOMATION,
    cost: 7700,
    preTechList: [eTechnology.TECH_ROCKETRY, eTechnology.TECH_COMPUTERS],
  },
  {
    id: eTechnology.TECH_LASERS,
    name: "镭射",
    era: eEra.ERA_INFOMATION,
    cost: 7700,
    preTechList: [eTechnology.TECH_COMPUTERS],
  },
  {
    id: eTechnology.TECH_INTERNET,
    name: "网络",
    era: eEra.ERA_INFOMATION,
    cost: 8800,
    preTechList: [eTechnology.TECH_TELECOM],
  },
  {
    id: eTechnology.TECH_GLOBALIZATION,
    name: "全球化",
    era: eEra.ERA_INFOMATION,
    cost: 8800,
    preTechList: [eTechnology.TECH_TELECOM],
  },
  {
    id: eTechnology.TECH_PARTICLE_PHYSICS,
    name: "粒子物理学",
    era: eEra.ERA_INFOMATION,
    cost: 8800,
    preTechList: [
      eTechnology.TECH_TELECOM,
      eTechnology.TECH_MOBILE_TACTICS,
      eTechnology.TECH_ADVANCED_BALLISTICS,
    ],
  },
  {
    id: eTechnology.TECH_NUCLEAR_FUSION,
    name: "核聚变",
    era: eEra.ERA_INFOMATION,
    cost: 8800,
    preTechList: [
      eTechnology.TECH_ROBOTICS,
      eTechnology.TECH_SATELLITES,
      eTechnology.TECH_ADVANCED_BALLISTICS,
    ],
  },
  {
    id: eTechnology.TECH_NANOTECHNOLOGY,
    name: "纳米科技",
    era: eEra.ERA_INFOMATION,
    cost: 8800,
    preTechList: [eTechnology.TECH_ROBOTICS],
  },
  {
    id: eTechnology.TECH_STEALTH,
    name: "隐形技术",
    era: eEra.ERA_INFOMATION,
    cost: 8800,
    preTechList: [eTechnology.TECH_ROBOTICS, eTechnology.TECH_LASERS],
  },

  /*future*/
  {
    id: eTechnology.TECH_FUTURE_TECH,
    name: "未来科技",
    era: eEra.ERA_FUTURE,
    cost: 9500,
    preTechList: [
      eTechnology.TECH_INTERNET,
      eTechnology.TECH_GLOBALIZATION,
      eTechnology.TECH_PARTICLE_PHYSICS,
      eTechnology.TECH_NUCLEAR_FUSION,
      eTechnology.TECH_NANOTECHNOLOGY,
      eTechnology.TECH_STEALTH,
    ],
  },
];
