import { UnitModel } from "@/types/commonType";
import {
  eEra,
  eNationality,
  eTechnology,
  ePromotion,
  eUnitType,
  eUnit,
  eUnitResource,
} from "@/staticData/enums";

export const battleUnitArray: Array<UnitModel> = [
  {
    id: eUnit.UNIT_CITY,
    name: "城市",
    era: eEra.ERA_ANCIENT,
    type: eUnitType.UNIT_TYPE_CITY,
    nationality: eNationality.NATION_NONE,
    substitution: eUnit.UNIT_NONE,
    upgrade: eUnit.UNIT_NONE,
    cost: 0,
    closeCombat: false,
    attackRange: 2,
    attackValue: 0,
    rangeAttackValue: 0,
    terrainDefense: false,
    originPromotion: [],
    movement: 0,
    resource: eUnitResource.UNIT_RESOURCE_NONE,
    startTechnology: eTechnology.TECH_AGRICULTURE,
    endTechnology: eTechnology.TECH_AGRICULTURE,
    iconSrc: "UNIT_CITY.png",
  },
  {
    id: eUnit.UNIT_SCOUT,
    name: "斥候",
    era: eEra.ERA_ANCIENT,
    type: eUnitType.UNIT_TYPE_DETECT,
    nationality: eNationality.NATION_NONE,
    substitution: eUnit.UNIT_NONE,
    upgrade: eUnit.UNIT_NONE,
    cost: 25,
    closeCombat: true,
    attackRange: 1,
    attackValue: 5,
    rangeAttackValue: 5,
    terrainDefense: true,
    originPromotion: [],
    movement: 2,
    resource: eUnitResource.UNIT_RESOURCE_NONE,
    startTechnology: eTechnology.TECH_AGRICULTURE,
    endTechnology: eTechnology.TECH_AGRICULTURE,
    iconSrc: "UNIT_SCOUT.png",
  },
  {
    id: eUnit.UNIT_SHOSHONE_PATHFINDER,
    name: "探路者",
    era: eEra.ERA_ANCIENT,
    type: eUnitType.UNIT_TYPE_DETECT,
    nationality: eNationality.NATION_SHOSHONE,
    substitution: eUnit.UNIT_SCOUT,
    upgrade: eUnit.UNIT_NONE,
    cost: 45,
    closeCombat: true,
    attackRange: 1,
    attackValue: 8,
    rangeAttackValue: 8,
    terrainDefense: true,
    originPromotion: [],
    movement: 2,
    resource: eUnitResource.UNIT_RESOURCE_NONE,
    startTechnology: eTechnology.TECH_AGRICULTURE,
    endTechnology: eTechnology.TECH_AGRICULTURE,
    iconSrc: "UNIT_SHOSHONE_PATHFINDER.png",
  },
  {
    id: eUnit.UNIT_GALLEY,
    name: "桨帆船",
    era: eEra.ERA_ANCIENT,
    type: eUnitType.UNIT_TYPE_SEACLOSECOMBAT,
    nationality: eNationality.NATION_BARBARIAN,
    substitution: eUnit.UNIT_NONE,
    upgrade: eUnit.UNIT_TRIREME,
    cost: 40,
    closeCombat: true,
    attackRange: 1,
    attackValue: 7,
    rangeAttackValue: 7,
    terrainDefense: true,
    originPromotion: [],
    movement: 3,
    resource: eUnitResource.UNIT_RESOURCE_NONE,
    startTechnology: eTechnology.TECH_AGRICULTURE,
    endTechnology: eTechnology.TECH_AGRICULTURE,
    iconSrc: "UNIT_GALLEY.png",
  },
  {
    id: eUnit.UNIT_TRIREME,
    name: "三列桨帆船",
    era: eEra.ERA_ANCIENT,
    type: eUnitType.UNIT_TYPE_SEACLOSECOMBAT,
    nationality: eNationality.NATION_NONE,
    substitution: eUnit.UNIT_NONE,
    upgrade: eUnit.UNIT_NONE,
    cost: 45,
    closeCombat: true,
    attackRange: 1,
    attackValue: 10,
    rangeAttackValue: 10,
    terrainDefense: true,
    originPromotion: [],
    movement: 4,
    resource: eUnitResource.UNIT_RESOURCE_NONE,
    startTechnology: eTechnology.TECH_SAILING,
    endTechnology: eTechnology.TECH_ASTRONOMY,
    iconSrc: "UNIT_TRIREME.png",
  },
  {
    id: eUnit.UNIT_CARTHAGINIAN_QUINQUEREME,
    name: "五列桨战船",
    era: eEra.ERA_ANCIENT,
    type: eUnitType.UNIT_TYPE_SEACLOSECOMBAT,
    nationality: eNationality.NATION_CARTHAGE,
    substitution: eUnit.UNIT_TRIREME,
    upgrade: eUnit.UNIT_NONE,
    cost: 45,
    closeCombat: true,
    attackRange: 1,
    attackValue: 13,
    rangeAttackValue: 13,
    terrainDefense: true,
    originPromotion: [],
    movement: 4,
    resource: eUnitResource.UNIT_RESOURCE_NONE,
    startTechnology: eTechnology.TECH_SAILING,
    endTechnology: eTechnology.TECH_ASTRONOMY,
    iconSrc: "UNIT_CARTHAGINIAN_QUINQUEREME.png",
  },
  {
    id: eUnit.UNIT_BYZANTINE_DROMON,
    name: "喷火船",
    era: eEra.ERA_ANCIENT,
    type: eUnitType.UNIT_TYPE_SEAREMOTE,
    nationality: eNationality.NATION_BYZANTIUM,
    substitution: eUnit.UNIT_TRIREME,
    upgrade: eUnit.UNIT_NONE,
    cost: 56,
    closeCombat: false,
    attackRange: 2,
    attackValue: 8,
    rangeAttackValue: 10,
    terrainDefense: true,
    originPromotion: [ePromotion.PROMOTION_STINGOUT],
    movement: 4,
    resource: eUnitResource.UNIT_RESOURCE_NONE,
    startTechnology: eTechnology.TECH_SAILING,
    endTechnology: eTechnology.TECH_ASTRONOMY,
    iconSrc: "UNIT_BYZANTINE_DROMON.png",
  },
  {
    id: eUnit.UNIT_CHARIOT_ARCHER,
    name: "弓弩战车",
    era: eEra.ERA_ANCIENT,
    type: eUnitType.UNIT_TYPE_REMOTE,
    nationality: eNationality.NATION_NONE,
    substitution: eUnit.UNIT_NONE,
    upgrade: eUnit.UNIT_NONE,
    cost: 56,
    closeCombat: false,
    attackRange: 2,
    attackValue: 6,
    rangeAttackValue: 10,
    terrainDefense: false,
    originPromotion: [],
    movement: 4,
    resource: eUnitResource.UNIT_RESOURCE_HORSE,
    startTechnology: eTechnology.TECH_THE_WHEEL,
    endTechnology: eTechnology.TECH_CHIVALRY,
    iconSrc: "UNIT_CHARIOT_ARCHER.png",
  },
  {
    id: eUnit.UNIT_INDIAN_WARELEPHANT,
    name: "战象",
    era: eEra.ERA_ANCIENT,
    type: eUnitType.UNIT_TYPE_REMOTE,
    nationality: eNationality.NATION_INDIA,
    substitution: eUnit.UNIT_CHARIOT_ARCHER,
    upgrade: eUnit.UNIT_NONE,
    cost: 70,
    closeCombat: false,
    attackRange: 2,
    attackValue: 9,
    rangeAttackValue: 11,
    terrainDefense: false,
    originPromotion: [],
    movement: 3,
    resource: eUnitResource.UNIT_RESOURCE_NONE,
    startTechnology: eTechnology.TECH_THE_WHEEL,
    endTechnology: eTechnology.TECH_CHIVALRY,
    iconSrc: "UNIT_INDIAN_WARELEPHANT.png",
  },
  {
    id: eUnit.UNIT_EGYPTIAN_WARCHARIOT,
    name: "战车",
    era: eEra.ERA_ANCIENT,
    type: eUnitType.UNIT_TYPE_REMOTE,
    nationality: eNationality.NATION_EGYPT,
    substitution: eUnit.UNIT_CHARIOT_ARCHER,
    upgrade: eUnit.UNIT_NONE,
    cost: 56,
    closeCombat: false,
    attackRange: 2,
    attackValue: 6,
    rangeAttackValue: 10,
    terrainDefense: false,
    originPromotion: [],
    movement: 5,
    resource: eUnitResource.UNIT_RESOURCE_NONE,
    startTechnology: eTechnology.TECH_THE_WHEEL,
    endTechnology: eTechnology.TECH_CHIVALRY,
    iconSrc: "UNIT_EGYPTIAN_WARCHARIOT.png",
  },
  {
    id: eUnit.UNIT_BARBARIAN_AXMAN,
    name: "掷斧手",
    era: eEra.ERA_ANCIENT,
    type: eUnitType.UNIT_TYPE_REMOTE,
    nationality: eNationality.NATION_BARBARIAN,
    substitution: eUnit.UNIT_CHARIOT_ARCHER,
    upgrade: eUnit.UNIT_NONE,
    cost: 56,
    closeCombat: false,
    attackRange: 1,
    attackValue: 9,
    rangeAttackValue: 9,
    terrainDefense: true,
    originPromotion: [],
    movement: 2,
    resource: eUnitResource.UNIT_RESOURCE_NONE,
    startTechnology: eTechnology.TECH_THE_WHEEL,
    endTechnology: eTechnology.TECH_CHIVALRY,
    iconSrc: "UNIT_BARBARIAN_AXMAN.png",
  },
  {
    id: eUnit.UNIT_HUN_HORSE_ARCHER,
    name: "骑射手",
    era: eEra.ERA_ANCIENT,
    type: eUnitType.UNIT_TYPE_REMOTE,
    nationality: eNationality.NATION_HUN,
    substitution: eUnit.UNIT_CHARIOT_ARCHER,
    upgrade: eUnit.UNIT_NONE,
    cost: 56,
    closeCombat: false,
    attackRange: 2,
    attackValue: 7,
    rangeAttackValue: 10,
    terrainDefense: false,
    originPromotion: [ePromotion.PROMOTION_ACCURACY_I],
    movement: 4,
    resource: eUnitResource.UNIT_RESOURCE_NONE,
    startTechnology: eTechnology.TECH_THE_WHEEL,
    endTechnology: eTechnology.TECH_CHIVALRY,
    iconSrc: "UNIT_HUN_HORSE_ARCHER.png",
  },
  {
    id: eUnit.UNIT_ARCHER,
    name: "弓箭手",
    era: eEra.ERA_ANCIENT,
    type: eUnitType.UNIT_TYPE_REMOTE,
    nationality: eNationality.NATION_NONE,
    substitution: eUnit.UNIT_NONE,
    upgrade: eUnit.UNIT_NONE,
    cost: 40,
    closeCombat: false,
    attackRange: 2,
    attackValue: 5,
    rangeAttackValue: 7,
    terrainDefense: true,
    originPromotion: [],
    movement: 2,
    resource: eUnitResource.UNIT_RESOURCE_NONE,
    startTechnology: eTechnology.TECH_ARCHERY,
    endTechnology: eTechnology.TECH_CONSTRUCTION,
    iconSrc: "UNIT_ARCHER.png",
  },
  {
    id: eUnit.UNIT_BABYLONIAN_BOWMAN,
    name: "巴比伦弓",
    era: eEra.ERA_ANCIENT,
    type: eUnitType.UNIT_TYPE_REMOTE,
    nationality: eNationality.NATION_BABYLON,
    substitution: eUnit.UNIT_ARCHER,
    upgrade: eUnit.UNIT_NONE,
    cost: 40,
    closeCombat: false,
    attackRange: 2,
    attackValue: 7,
    rangeAttackValue: 9,
    terrainDefense: true,
    originPromotion: [],
    movement: 2,
    resource: eUnitResource.UNIT_RESOURCE_NONE,
    startTechnology: eTechnology.TECH_ARCHERY,
    endTechnology: eTechnology.TECH_CONSTRUCTION,
    iconSrc: "UNIT_BABYLONIAN_BOWMAN.png",
  },
  {
    id: eUnit.UNIT_MAYAN_ATLATLIST,
    name: "掷矛战士",
    era: eEra.ERA_ANCIENT,
    type: eUnitType.UNIT_TYPE_REMOTE,
    nationality: eNationality.NATION_MAYA,
    substitution: eUnit.UNIT_ARCHER,
    upgrade: eUnit.UNIT_NONE,
    cost: 36,
    closeCombat: false,
    attackRange: 2,
    attackValue: 5,
    rangeAttackValue: 7,
    terrainDefense: true,
    originPromotion: [],
    movement: 2,
    resource: eUnitResource.UNIT_RESOURCE_NONE,
    startTechnology: eTechnology.TECH_AGRICULTURE,
    endTechnology: eTechnology.TECH_CONSTRUCTION,
    iconSrc: "UNIT_MAYAN_ATLATLIST.png",
  },
  {
    id: eUnit.UNIT_INCAN_SLINGER,
    name: "掷石手",
    era: eEra.ERA_ANCIENT,
    type: eUnitType.UNIT_TYPE_REMOTE,
    nationality: eNationality.NATION_INCA,
    substitution: eUnit.UNIT_ARCHER,
    upgrade: eUnit.UNIT_NONE,
    cost: 40,
    closeCombat: false,
    attackRange: 2,
    attackValue: 4,
    rangeAttackValue: 7,
    terrainDefense: true,
    originPromotion: [],
    movement: 2,
    resource: eUnitResource.UNIT_RESOURCE_NONE,
    startTechnology: eTechnology.TECH_AGRICULTURE,
    endTechnology: eTechnology.TECH_CONSTRUCTION,
    iconSrc: "UNIT_INCAN_SLINGER.png",
  },
  {
    id: eUnit.UNIT_SPEARMAN,
    name: "长矛兵",
    era: eEra.ERA_ANCIENT,
    type: eUnitType.UNIT_TYPE_CLOSECOMBAT,
    nationality: eNationality.NATION_NONE,
    substitution: eUnit.UNIT_NONE,
    upgrade: eUnit.UNIT_NONE,
    cost: 56,
    closeCombat: true,
    attackRange: 1,
    attackValue: 11,
    rangeAttackValue: 11,
    terrainDefense: true,
    originPromotion: [ePromotion.PROMOTION_COUTER_RIDING],
    movement: 2,
    resource: eUnitResource.UNIT_RESOURCE_NONE,
    startTechnology: eTechnology.TECH_BRONZE_WORKING,
    endTechnology: eTechnology.TECH_CIVIL_SERVICE,
    iconSrc: "UNIT_SPEARMAN.png",
  },
  {
    id: eUnit.UNIT_CELT_PICTISH_WARRIOR,
    name: "皮克特战士",
    era: eEra.ERA_ANCIENT,
    type: eUnitType.UNIT_TYPE_CLOSECOMBAT,
    nationality: eNationality.NATION_CELTIC,
    substitution: eUnit.UNIT_SPEARMAN,
    upgrade: eUnit.UNIT_NONE,
    cost: 56,
    closeCombat: true,
    attackRange: 1,
    attackValue: 11,
    rangeAttackValue: 11,
    terrainDefense: true,
    originPromotion: [],
    movement: 2,
    resource: eUnitResource.UNIT_RESOURCE_NONE,
    startTechnology: eTechnology.TECH_BRONZE_WORKING,
    endTechnology: eTechnology.TECH_CIVIL_SERVICE,
    iconSrc: "UNIT_CELT_PICTISH_WARRIOR.png",
  },
  {
    id: eUnit.UNIT_GREEK_HOPLITE,
    name: "重装步兵",
    era: eEra.ERA_ANCIENT,
    type: eUnitType.UNIT_TYPE_CLOSECOMBAT,
    nationality: eNationality.NATION_GREECE,
    substitution: eUnit.UNIT_SPEARMAN,
    upgrade: eUnit.UNIT_NONE,
    cost: 56,
    closeCombat: true,
    attackRange: 1,
    attackValue: 13,
    rangeAttackValue: 13,
    terrainDefense: true,
    originPromotion: [ePromotion.PROMOTION_COUTER_RIDING],
    movement: 2,
    resource: eUnitResource.UNIT_RESOURCE_NONE,
    startTechnology: eTechnology.TECH_BRONZE_WORKING,
    endTechnology: eTechnology.TECH_CIVIL_SERVICE,
    iconSrc: "UNIT_GREEK_HOPLITE.png",
  },
  {
    id: eUnit.UNIT_PERSIAN_IMMORTAL,
    name: "长生军",
    era: eEra.ERA_ANCIENT,
    type: eUnitType.UNIT_TYPE_CLOSECOMBAT,
    nationality: eNationality.NATION_PERSIA,
    substitution: eUnit.UNIT_SPEARMAN,
    upgrade: eUnit.UNIT_NONE,
    cost: 56,
    closeCombat: true,
    attackRange: 1,
    attackValue: 12,
    rangeAttackValue: 12,
    terrainDefense: true,
    originPromotion: [ePromotion.PROMOTION_COUTER_RIDING],
    movement: 2,
    resource: eUnitResource.UNIT_RESOURCE_NONE,
    startTechnology: eTechnology.TECH_BRONZE_WORKING,
    endTechnology: eTechnology.TECH_CIVIL_SERVICE,
    iconSrc: "UNIT_PERSIAN_IMMORTAL.png",
  },
  {
    id: eUnit.UNIT_HUN_BATTERING_RAM,
    name: "冲车",
    era: eEra.ERA_ANCIENT,
    type: eUnitType.UNIT_TYPE_CLOSECOMBAT,
    nationality: eNationality.NATION_HUN,
    substitution: eUnit.UNIT_SPEARMAN,
    upgrade: eUnit.UNIT_NONE,
    cost: 75,
    closeCombat: true,
    attackRange: 1,
    attackValue: 10,
    rangeAttackValue: 10,
    terrainDefense: false,
    originPromotion: [ePromotion.PROMOTION_COUNTER_CITY_300],
    movement: 2,
    resource: eUnitResource.UNIT_RESOURCE_NONE,
    startTechnology: eTechnology.TECH_BRONZE_WORKING,
    endTechnology: eTechnology.TECH_PHYSICS,
    iconSrc: "UNIT_HUN_BATTERING_RAM.png",
  },
  {
    id: eUnit.UNIT_WARRIOR,
    name: "战士",
    era: eEra.ERA_ANCIENT,
    type: eUnitType.UNIT_TYPE_CLOSECOMBAT,
    nationality: eNationality.NATION_NONE,
    substitution: eUnit.UNIT_NONE,
    upgrade: eUnit.UNIT_NONE,
    cost: 40,
    closeCombat: true,
    attackRange: 1,
    attackValue: 8,
    rangeAttackValue: 8,
    terrainDefense: true,
    originPromotion: [],
    movement: 2,
    resource: eUnitResource.UNIT_RESOURCE_NONE,
    startTechnology: eTechnology.TECH_AGRICULTURE,
    endTechnology: eTechnology.TECH_METAL_CASTING,
    iconSrc: "UNIT_WARRIOR.png",
  },
  {
    id: eUnit.UNIT_AZTEC_JAGUAR,
    name: "美洲虎战士",
    era: eEra.ERA_ANCIENT,
    type: eUnitType.UNIT_TYPE_CLOSECOMBAT,
    nationality: eNationality.NATION_AZTAKA,
    substitution: eUnit.UNIT_WARRIOR,
    upgrade: eUnit.UNIT_NONE,
    cost: 40,
    closeCombat: true,
    attackRange: 1,
    attackValue: 8,
    rangeAttackValue: 8,
    terrainDefense: true,
    originPromotion: [ePromotion.PROMOTION_JUNGLE_ROGUE],
    movement: 2,
    resource: eUnitResource.UNIT_RESOURCE_NONE,
    startTechnology: eTechnology.TECH_AGRICULTURE,
    endTechnology: eTechnology.TECH_METAL_CASTING,
    iconSrc: "UNIT_AZTEC_JAGUAR.png",
  },
  {
    id: eUnit.UNIT_POLYNESIAN_MAORI_WARRIOR,
    name: "毛利勇士",
    era: eEra.ERA_ANCIENT,
    type: eUnitType.UNIT_TYPE_CLOSECOMBAT,
    nationality: eNationality.NATION_POLYNESIA,
    substitution: eUnit.UNIT_WARRIOR,
    upgrade: eUnit.UNIT_NONE,
    cost: 40,
    closeCombat: true,
    attackRange: 1,
    attackValue: 8,
    rangeAttackValue: 8,
    terrainDefense: true,
    originPromotion: [ePromotion.PROMOTION_HAKKAR_DANCE],
    movement: 2,
    resource: eUnitResource.UNIT_RESOURCE_NONE,
    startTechnology: eTechnology.TECH_AGRICULTURE,
    endTechnology: eTechnology.TECH_METAL_CASTING,
    iconSrc: "UNIT_POLYNESIAN_MAORI_WARRIOR.png",
  },
  {
    id: eUnit.UNIT_CATAPULT,
    name: "投石车",
    era: eEra.ERA_CLASSICAL,
    type: eUnitType.UNIT_TYPE_SIEGE,
    nationality: eNationality.NATION_NONE,
    substitution: eUnit.UNIT_NONE,
    upgrade: eUnit.UNIT_NONE,
    cost: 75,
    closeCombat: false,
    attackRange: 2,
    attackValue: 7,
    rangeAttackValue: 8,
    terrainDefense: false,
    originPromotion: [ePromotion.PROMOTION_COUNTER_CITY_200],
    movement: 2,
    resource: eUnitResource.UNIT_RESOURCE_NONE,
    startTechnology: eTechnology.TECH_MATHEMATICS,
    endTechnology: eTechnology.TECH_PHYSICS,
    iconSrc: "UNIT_CATAPULT.png",
  },
  {
    id: eUnit.UNIT_ROMAN_BALLISTA,
    name: "弩炮",
    era: eEra.ERA_CLASSICAL,
    type: eUnitType.UNIT_TYPE_SIEGE,
    nationality: eNationality.NATION_ROMA,
    substitution: eUnit.UNIT_CATAPULT,
    upgrade: eUnit.UNIT_NONE,
    cost: 75,
    closeCombat: false,
    attackRange: 2,
    attackValue: 8,
    rangeAttackValue: 10,
    terrainDefense: false,
    originPromotion: [ePromotion.PROMOTION_COUNTER_CITY_200],
    movement: 2,
    resource: eUnitResource.UNIT_RESOURCE_NONE,
    startTechnology: eTechnology.TECH_MATHEMATICS,
    endTechnology: eTechnology.TECH_PHYSICS,
    iconSrc: "UNIT_ROMAN_BALLISTA.png",
  },
  {
    id: eUnit.UNIT_ASSYRIAN_SIEGE_TOWER,
    name: "攻城塔",
    era: eEra.ERA_CLASSICAL,
    type: eUnitType.UNIT_TYPE_SIEGE,
    nationality: eNationality.NATION_ASSYRIA,
    substitution: eUnit.UNIT_CATAPULT,
    upgrade: eUnit.UNIT_NONE,
    cost: 75,
    closeCombat: true,
    attackRange: 1,
    attackValue: 12,
    rangeAttackValue: 12,
    terrainDefense: false,
    originPromotion: [
      ePromotion.PROMOTION_COVER_I,
      ePromotion.PROMOTION_COUNTER_CITY_200,
    ],
    movement: 2,
    resource: eUnitResource.UNIT_RESOURCE_NONE,
    startTechnology: eTechnology.TECH_MATHEMATICS,
    endTechnology: eTechnology.TECH_PHYSICS,
    iconSrc: "UNIT_ASSYRIAN_SIEGE_TOWER.png",
  },
  {
    id: eUnit.UNIT_SWORDSMAN,
    name: "剑士",
    era: eEra.ERA_CLASSICAL,
    type: eUnitType.UNIT_TYPE_CLOSECOMBAT,
    nationality: eNationality.NATION_NONE,
    substitution: eUnit.UNIT_NONE,
    upgrade: eUnit.UNIT_NONE,
    cost: 75,
    closeCombat: true,
    attackRange: 1,
    attackValue: 14,
    rangeAttackValue: 14,
    terrainDefense: true,
    originPromotion: [],
    movement: 2,
    resource: eUnitResource.UNIT_RESOURCE_IRON,
    startTechnology: eTechnology.TECH_IRON_WORKING,
    endTechnology: eTechnology.TECH_STEEL,
    iconSrc: "UNIT_SWORDSMAN.png",
  },
  {
    id: eUnit.UNIT_ROMAN_LEGION,
    name: "军团",
    era: eEra.ERA_CLASSICAL,
    type: eUnitType.UNIT_TYPE_CLOSECOMBAT,
    nationality: eNationality.NATION_ROMA,
    substitution: eUnit.UNIT_SWORDSMAN,
    upgrade: eUnit.UNIT_NONE,
    cost: 75,
    closeCombat: true,
    attackRange: 1,
    attackValue: 17,
    rangeAttackValue: 17,
    terrainDefense: true,
    originPromotion: [],
    movement: 2,
    resource: eUnitResource.UNIT_RESOURCE_IRON,
    startTechnology: eTechnology.TECH_IRON_WORKING,
    endTechnology: eTechnology.TECH_STEEL,
    iconSrc: "UNIT_ROMAN_LEGION.png",
  },
  {
    id: eUnit.UNIT_IROQUOIAN_MOHAWKWARRIOR,
    name: "莫霍克战士",
    era: eEra.ERA_CLASSICAL,
    type: eUnitType.UNIT_TYPE_CLOSECOMBAT,
    nationality: eNationality.NATION_IROQUOIS,
    substitution: eUnit.UNIT_SWORDSMAN,
    upgrade: eUnit.UNIT_NONE,
    cost: 75,
    closeCombat: true,
    attackRange: 1,
    attackValue: 14,
    rangeAttackValue: 14,
    terrainDefense: true,
    originPromotion: [ePromotion.PROMOTION_JUNGLE_ROGUE],
    movement: 2,
    resource: eUnitResource.UNIT_RESOURCE_NONE,
    startTechnology: eTechnology.TECH_IRON_WORKING,
    endTechnology: eTechnology.TECH_STEEL,
    iconSrc: "UNIT_ROMAN_LEGION.png",
  },
  {
    id: eUnit.UNIT_KRIS_SWORDSMAN,
    name: "波刃剑士",
    era: eEra.ERA_CLASSICAL,
    type: eUnitType.UNIT_TYPE_CLOSECOMBAT,
    nationality: eNationality.NATION_INDONESIA,
    substitution: eUnit.UNIT_SWORDSMAN,
    upgrade: eUnit.UNIT_NONE,
    cost: 75,
    closeCombat: true,
    attackRange: 1,
    attackValue: 14,
    rangeAttackValue: 14,
    terrainDefense: true,
    originPromotion: [],
    movement: 2,
    resource: eUnitResource.UNIT_RESOURCE_IRON,
    startTechnology: eTechnology.TECH_IRON_WORKING,
    endTechnology: eTechnology.TECH_STEEL,
    iconSrc: "UNIT_KRIS_SWORDSMAN.png",
  },
  {
    id: eUnit.UNIT_HORSEMAN,
    name: "骑手",
    era: eEra.ERA_CLASSICAL,
    type: eUnitType.UNIT_TYPE_RIDING,
    nationality: eNationality.NATION_NONE,
    substitution: eUnit.UNIT_NONE,
    upgrade: eUnit.UNIT_NONE,
    cost: 75,
    closeCombat: true,
    attackRange: 1,
    attackValue: 12,
    rangeAttackValue: 12,
    terrainDefense: false,
    originPromotion: [ePromotion.PROMOTION_DEBUFF_CITY_33],
    movement: 4,
    resource: eUnitResource.UNIT_RESOURCE_HORSE,
    startTechnology: eTechnology.TECH_HORSEBACK_RIDING,
    endTechnology: eTechnology.TECH_CHIVALRY,
    iconSrc: "UNIT_HORSEMAN.png",
  },
  {
    id: eUnit.UNIT_GREEK_COMPANIONCAVALRY,
    name: "王伴骑兵",
    era: eEra.ERA_CLASSICAL,
    type: eUnitType.UNIT_TYPE_RIDING,
    nationality: eNationality.NATION_GREECE,
    substitution: eUnit.UNIT_HORSEMAN,
    upgrade: eUnit.UNIT_NONE,
    cost: 75,
    closeCombat: true,
    attackRange: 1,
    attackValue: 14,
    rangeAttackValue: 14,
    terrainDefense: false,
    originPromotion: [ePromotion.PROMOTION_DEBUFF_CITY_33],
    movement: 5,
    resource: eUnitResource.UNIT_RESOURCE_HORSE,
    startTechnology: eTechnology.TECH_HORSEBACK_RIDING,
    endTechnology: eTechnology.TECH_CHIVALRY,
    iconSrc: "UNIT_GREEK_COMPANIONCAVALRY.png",
  },
  {
    id: eUnit.UNIT_CARTHAGINIAN_FOREST_ELEPHANT,
    name: "非洲森林象",
    era: eEra.ERA_CLASSICAL,
    type: eUnitType.UNIT_TYPE_RIDING,
    nationality: eNationality.NATION_CARTHAGE,
    substitution: eUnit.UNIT_HORSEMAN,
    upgrade: eUnit.UNIT_NONE,
    cost: 100,
    closeCombat: true,
    attackRange: 1,
    attackValue: 14,
    rangeAttackValue: 14,
    terrainDefense: false,
    originPromotion: [
      ePromotion.PROMOTION_DEBUFF_CITY_33,
      ePromotion.PROMOTION_ELEPHANT_SCARE,
    ],
    movement: 3,
    resource: eUnitResource.UNIT_RESOURCE_NONE,
    startTechnology: eTechnology.TECH_HORSEBACK_RIDING,
    endTechnology: eTechnology.TECH_CHIVALRY,
    iconSrc: "UNIT_CARTHAGINIAN_FOREST_ELEPHANT.png",
  },
  {
    id: eUnit.UNIT_BYZANTINE_CATAPHRACT,
    name: "铁甲骑兵",
    era: eEra.ERA_CLASSICAL,
    type: eUnitType.UNIT_TYPE_RIDING,
    nationality: eNationality.NATION_BYZANTIUM,
    substitution: eUnit.UNIT_HORSEMAN,
    upgrade: eUnit.UNIT_NONE,
    cost: 75,
    closeCombat: true,
    attackRange: 1,
    attackValue: 15,
    rangeAttackValue: 15,
    terrainDefense: true,
    originPromotion: [ePromotion.PROMOTION_DEBUFF_CITY_25],
    movement: 3,
    resource: eUnitResource.UNIT_RESOURCE_HORSE,
    startTechnology: eTechnology.TECH_HORSEBACK_RIDING,
    endTechnology: eTechnology.TECH_CHIVALRY,
    iconSrc: "UNIT_BYZANTINE_CATAPHRACT.png",
  },
  {
    id: eUnit.UNIT_COMPOSITE_BOWMAN,
    name: "复合弓手",
    era: eEra.ERA_CLASSICAL,
    type: eUnitType.UNIT_TYPE_REMOTE,
    nationality: eNationality.NATION_NONE,
    substitution: eUnit.UNIT_NONE,
    upgrade: eUnit.UNIT_NONE,
    cost: 75,
    closeCombat: false,
    attackRange: 2,
    attackValue: 7,
    rangeAttackValue: 11,
    terrainDefense: true,
    originPromotion: [],
    movement: 2,
    resource: eUnitResource.UNIT_RESOURCE_NONE,
    startTechnology: eTechnology.TECH_CONSTRUCTION,
    endTechnology: eTechnology.TECH_MACHINERY,
    iconSrc: "UNIT_COMPOSITE_BOWMAN.png",
  },
  {
    id: eUnit.UNIT_GALLEASS,
    name: "加莱宝战船",
    era: eEra.ERA_MEDIEVAL,
    type: eUnitType.UNIT_TYPE_SEAREMOTE,
    nationality: eNationality.NATION_NONE,
    substitution: eUnit.UNIT_NONE,
    upgrade: eUnit.UNIT_NONE,
    cost: 110,
    closeCombat: false,
    attackRange: 2,
    attackValue: 16,
    rangeAttackValue: 17,
    terrainDefense: true,
    originPromotion: [],
    movement: 3,
    resource: eUnitResource.UNIT_RESOURCE_NONE,
    startTechnology: eTechnology.TECH_COMPASS,
    endTechnology: eTechnology.TECH_NAVIGATION,
    iconSrc: "UNIT_GALLEASS.png",
  },
  {
    id: eUnit.UNIT_VENETIAN_GALLEASS,
    name: "大加莱宝战船",
    era: eEra.ERA_MEDIEVAL,
    type: eUnitType.UNIT_TYPE_SEAREMOTE,
    nationality: eNationality.NATION_VENICE,
    substitution: eUnit.UNIT_GALLEASS,
    upgrade: eUnit.UNIT_NONE,
    cost: 100,
    closeCombat: false,
    attackRange: 2,
    attackValue: 18,
    rangeAttackValue: 20,
    terrainDefense: true,
    originPromotion: [],
    movement: 3,
    resource: eUnitResource.UNIT_RESOURCE_NONE,
    startTechnology: eTechnology.TECH_COMPASS,
    endTechnology: eTechnology.TECH_NAVIGATION,
    iconSrc: "UNIT_VENETIAN_GALLEASS.png",
  },
  {
    id: eUnit.UNIT_TREBUCHET,
    name: "投石机",
    era: eEra.ERA_MEDIEVAL,
    type: eUnitType.UNIT_TYPE_SIEGE,
    nationality: eNationality.NATION_NONE,
    substitution: eUnit.UNIT_NONE,
    upgrade: eUnit.UNIT_NONE,
    cost: 120,
    closeCombat: false,
    attackRange: 2,
    attackValue: 12,
    rangeAttackValue: 14,
    terrainDefense: false,
    originPromotion: [ePromotion.PROMOTION_COUNTER_CITY_200],
    movement: 2,
    resource: eUnitResource.UNIT_RESOURCE_NONE,
    startTechnology: eTechnology.TECH_PHYSICS,
    endTechnology: eTechnology.TECH_CHEMISTRY,
    iconSrc: "UNIT_TREBUCHET.png",
  },
  {
    id: eUnit.UNIT_KOREAN_HWACHA,
    name: "火箱车",
    era: eEra.ERA_MEDIEVAL,
    type: eUnitType.UNIT_TYPE_SIEGE,
    nationality: eNationality.NATION_KOREA,
    substitution: eUnit.UNIT_TREBUCHET,
    upgrade: eUnit.UNIT_NONE,
    cost: 120,
    closeCombat: false,
    attackRange: 2,
    attackValue: 11,
    rangeAttackValue: 26,
    terrainDefense: false,
    originPromotion: [],
    movement: 2,
    resource: eUnitResource.UNIT_RESOURCE_NONE,
    startTechnology: eTechnology.TECH_PHYSICS,
    endTechnology: eTechnology.TECH_CHEMISTRY,
    iconSrc: "UNIT_KOREAN_HWACHA.png",
  },
  {
    id: eUnit.UNIT_GERMAN_LANDSKNECHT,
    name: "自由佣兵",
    era: eEra.ERA_MEDIEVAL,
    type: eUnitType.UNIT_TYPE_CLOSECOMBAT,
    nationality: eNationality.NATION_GERMANY,
    substitution: eUnit.UNIT_NONE,
    upgrade: eUnit.UNIT_NONE,
    cost: 45,
    closeCombat: true,
    attackRange: 1,
    attackValue: 16,
    rangeAttackValue: 16,
    terrainDefense: true,
    originPromotion: [ePromotion.PROMOTION_COUTER_RIDING],
    movement: 2,
    resource: eUnitResource.UNIT_RESOURCE_NONE,
    startTechnology: eTechnology.TECH_CIVIL_SERVICE,
    endTechnology: eTechnology.TECH_ARCHITECTURE,
    iconSrc: "UNIT_GERMAN_LANDSKNECHT.png",
  },
  {
    id: eUnit.UNIT_LONGSWORDSMAN,
    name: "长剑士",
    era: eEra.ERA_MEDIEVAL,
    type: eUnitType.UNIT_TYPE_CLOSECOMBAT,
    nationality: eNationality.NATION_NONE,
    substitution: eUnit.UNIT_NONE,
    upgrade: eUnit.UNIT_NONE,
    cost: 120,
    closeCombat: true,
    attackRange: 1,
    attackValue: 21,
    rangeAttackValue: 21,
    terrainDefense: true,
    originPromotion: [],
    movement: 2,
    resource: eUnitResource.UNIT_RESOURCE_IRON,
    startTechnology: eTechnology.TECH_STEEL,
    endTechnology: eTechnology.TECH_GUNPOWDER,
    iconSrc: "UNIT_LONGSWORDSMAN.png",
  },
  {
    id: eUnit.UNIT_DANISH_BERSERKER,
    name: "狂战士",
    era: eEra.ERA_MEDIEVAL,
    type: eUnitType.UNIT_TYPE_CLOSECOMBAT,
    nationality: eNationality.NATION_DENMARK,
    substitution: eUnit.UNIT_LONGSWORDSMAN,
    upgrade: eUnit.UNIT_NONE,
    cost: 120,
    closeCombat: true,
    attackRange: 1,
    attackValue: 21,
    rangeAttackValue: 21,
    terrainDefense: true,
    originPromotion: [],
    movement: 3,
    resource: eUnitResource.UNIT_RESOURCE_IRON,
    startTechnology: eTechnology.TECH_METAL_CASTING,
    endTechnology: eTechnology.TECH_METALLURGY,
    iconSrc: "UNIT_DANISH_BERSERKER.png",
  },
  {
    id: eUnit.UNIT_JAPANESE_SAMURAI,
    name: "武士",
    era: eEra.ERA_MEDIEVAL,
    type: eUnitType.UNIT_TYPE_CLOSECOMBAT,
    nationality: eNationality.NATION_JANPAN,
    substitution: eUnit.UNIT_LONGSWORDSMAN,
    upgrade: eUnit.UNIT_NONE,
    cost: 120,
    closeCombat: true,
    attackRange: 1,
    attackValue: 21,
    rangeAttackValue: 21,
    terrainDefense: true,
    originPromotion: [ePromotion.PROMOTION_SHOCK_I],
    movement: 2,
    resource: eUnitResource.UNIT_RESOURCE_IRON,
    startTechnology: eTechnology.TECH_STEEL,
    endTechnology: eTechnology.TECH_RIFLING,
    iconSrc: "UNIT_JAPANESE_SAMURAI.png",
  },
  {
    id: eUnit.UNIT_KNIGHT,
    name: "骑士",
    era: eEra.ERA_MEDIEVAL,
    type: eUnitType.UNIT_TYPE_RIDING,
    nationality: eNationality.NATION_NONE,
    substitution: eUnit.UNIT_NONE,
    upgrade: eUnit.UNIT_NONE,
    cost: 120,
    closeCombat: true,
    attackRange: 1,
    attackValue: 20,
    rangeAttackValue: 20,
    terrainDefense: false,
    originPromotion: [ePromotion.PROMOTION_DEBUFF_CITY_33],
    movement: 4,
    resource: eUnitResource.UNIT_RESOURCE_HORSE,
    startTechnology: eTechnology.TECH_CHIVALRY,
    endTechnology: eTechnology.TECH_MILITARY_SCIENCE,
    iconSrc: "UNIT_KNIGHT.png",
  },
  {
    id: eUnit.UNIT_MONGOLIAN_KESHIK,
    name: "怯薛",
    era: eEra.ERA_MEDIEVAL,
    type: eUnitType.UNIT_TYPE_REMOTE,
    nationality: eNationality.NATION_MONGOLIA,
    substitution: eUnit.UNIT_KNIGHT,
    upgrade: eUnit.UNIT_NONE,
    cost: 120,
    closeCombat: false,
    attackRange: 2,
    attackValue: 15,
    rangeAttackValue: 16,
    terrainDefense: false,
    originPromotion: [],
    movement: 5,
    resource: eUnitResource.UNIT_RESOURCE_HORSE,
    startTechnology: eTechnology.TECH_CHIVALRY,
    endTechnology: eTechnology.TECH_MILITARY_SCIENCE,
    iconSrc: "UNIT_MONGOLIAN_KESHIK.png",
  },
  {
    id: eUnit.UNIT_SPANISH_CONQUISTADOR,
    name: "征服者",
    era: eEra.ERA_MEDIEVAL,
    type: eUnitType.UNIT_TYPE_RIDING,
    nationality: eNationality.NATION_SPAIN,
    substitution: eUnit.UNIT_KNIGHT,
    upgrade: eUnit.UNIT_NONE,
    cost: 135,
    closeCombat: true,
    attackRange: 1,
    attackValue: 20,
    rangeAttackValue: 20,
    terrainDefense: false,
    originPromotion: [],
    movement: 4,
    resource: eUnitResource.UNIT_RESOURCE_HORSE,
    startTechnology: eTechnology.TECH_CHIVALRY,
    endTechnology: eTechnology.TECH_MILITARY_SCIENCE,
    iconSrc: "UNIT_SPANISH_CONQUISTADOR.png",
  },
  {
    id: eUnit.UNIT_SIAMESE_WARELEPHANT,
    name: "纳黎萱战象",
    era: eEra.ERA_MEDIEVAL,
    type: eUnitType.UNIT_TYPE_RIDING,
    nationality: eNationality.NATION_SIAM,
    substitution: eUnit.UNIT_KNIGHT,
    upgrade: eUnit.UNIT_NONE,
    cost: 120,
    closeCombat: true,
    attackRange: 1,
    attackValue: 25,
    rangeAttackValue: 25,
    terrainDefense: false,
    originPromotion: [
      ePromotion.PROMOTION_DEBUFF_CITY_33,
      ePromotion.PROMOTION_COUTER_RIDING,
    ],
    movement: 3,
    resource: eUnitResource.UNIT_RESOURCE_NONE,
    startTechnology: eTechnology.TECH_CHIVALRY,
    endTechnology: eTechnology.TECH_MILITARY_SCIENCE,
    iconSrc: "UNIT_SIAMESE_WARELEPHANT.png",
  },
  {
    id: eUnit.UNIT_SONGHAI_MUSLIMCAVALRY,
    name: "曼德卡鲁骑兵",
    era: eEra.ERA_MEDIEVAL,
    type: eUnitType.UNIT_TYPE_RIDING,
    nationality: eNationality.NATION_SONGHAI,
    substitution: eUnit.UNIT_KNIGHT,
    upgrade: eUnit.UNIT_NONE,
    cost: 120,
    closeCombat: true,
    attackRange: 1,
    attackValue: 20,
    rangeAttackValue: 20,
    terrainDefense: false,
    originPromotion: [],
    movement: 4,
    resource: eUnitResource.UNIT_RESOURCE_HORSE,
    startTechnology: eTechnology.TECH_CHIVALRY,
    endTechnology: eTechnology.TECH_MILITARY_SCIENCE,
    iconSrc: "UNIT_SONGHAI_MUSLIMCAVALRY.png",
  },
  {
    id: eUnit.UNIT_ARABIAN_CAMELARCHER,
    name: "骆驼骑射手",
    era: eEra.ERA_MEDIEVAL,
    type: eUnitType.UNIT_TYPE_REMOTE,
    nationality: eNationality.NATION_ARABIA,
    substitution: eUnit.UNIT_KNIGHT,
    upgrade: eUnit.UNIT_NONE,
    cost: 120,
    closeCombat: false,
    attackRange: 2,
    attackValue: 17,
    rangeAttackValue: 21,
    terrainDefense: false,
    originPromotion: [],
    movement: 4,
    resource: eUnitResource.UNIT_RESOURCE_HORSE,
    startTechnology: eTechnology.TECH_CHIVALRY,
    endTechnology: eTechnology.TECH_MILITARY_SCIENCE,
    iconSrc: "UNIT_ARABIAN_CAMELARCHER.png",
  },
  {
    id: eUnit.UNIT_CROSSBOWMAN,
    name: "弩兵",
    era: eEra.ERA_MEDIEVAL,
    type: eUnitType.UNIT_TYPE_REMOTE,
    nationality: eNationality.NATION_NONE,
    substitution: eUnit.UNIT_NONE,
    upgrade: eUnit.UNIT_NONE,
    cost: 120,
    closeCombat: false,
    attackRange: 2,
    attackValue: 13,
    rangeAttackValue: 18,
    terrainDefense: true,
    originPromotion: [],
    movement: 2,
    resource: eUnitResource.UNIT_RESOURCE_NONE,
    startTechnology: eTechnology.TECH_MACHINERY,
    endTechnology: eTechnology.TECH_INDUSTRIALIZATION,
    iconSrc: "UNIT_CROSSBOWMAN.png",
  },
  {
    id: eUnit.UNIT_ENGLISH_LONGBOWMAN,
    name: "长弓手",
    era: eEra.ERA_MEDIEVAL,
    type: eUnitType.UNIT_TYPE_REMOTE,
    nationality: eNationality.NATION_ENGLAND,
    substitution: eUnit.UNIT_CROSSBOWMAN,
    upgrade: eUnit.UNIT_NONE,
    cost: 120,
    closeCombat: false,
    attackRange: 2,
    attackValue: 13,
    rangeAttackValue: 18,
    terrainDefense: true,
    originPromotion: [],
    movement: 2,
    resource: eUnitResource.UNIT_RESOURCE_NONE,
    startTechnology: eTechnology.TECH_MACHINERY,
    endTechnology: eTechnology.TECH_INDUSTRIALIZATION,
    iconSrc: "UNIT_ENGLISH_LONGBOWMAN.png",
  },
  {
    id: eUnit.UNIT_CHINESE_CHUKONU,
    name: "诸葛弩兵",
    era: eEra.ERA_MEDIEVAL,
    type: eUnitType.UNIT_TYPE_REMOTE,
    nationality: eNationality.NATION_CHINA,
    substitution: eUnit.UNIT_CROSSBOWMAN,
    upgrade: eUnit.UNIT_NONE,
    cost: 120,
    closeCombat: false,
    attackRange: 2,
    attackValue: 13,
    rangeAttackValue: 14,
    terrainDefense: true,
    originPromotion: [],
    movement: 2,
    resource: eUnitResource.UNIT_RESOURCE_NONE,
    startTechnology: eTechnology.TECH_MACHINERY,
    endTechnology: eTechnology.TECH_INDUSTRIALIZATION,
    iconSrc: "UNIT_CHINESE_CHUKONU.png",
  },
  {
    id: eUnit.UNIT_PIKEMAN,
    name: "长枪兵",
    era: eEra.ERA_MEDIEVAL,
    type: eUnitType.UNIT_TYPE_CLOSECOMBAT,
    nationality: eNationality.NATION_NONE,
    substitution: eUnit.UNIT_NONE,
    upgrade: eUnit.UNIT_NONE,
    cost: 90,
    closeCombat: true,
    attackRange: 1,
    attackValue: 16,
    rangeAttackValue: 16,
    terrainDefense: true,
    originPromotion: [ePromotion.PROMOTION_COUTER_RIDING],
    movement: 2,
    resource: eUnitResource.UNIT_RESOURCE_NONE,
    startTechnology: eTechnology.TECH_CIVIL_SERVICE,
    endTechnology: eTechnology.TECH_METALLURGY,
    iconSrc: "UNIT_PIKEMAN.png",
  },
  {
    id: eUnit.UNIT_ZULU_IMPI,
    name: "斑图武士",
    era: eEra.ERA_MEDIEVAL,
    type: eUnitType.UNIT_TYPE_CLOSECOMBAT,
    nationality: eNationality.NATION_ZURU,
    substitution: eUnit.UNIT_PIKEMAN,
    upgrade: eUnit.UNIT_NONE,
    cost: 90,
    closeCombat: true,
    attackRange: 1,
    attackValue: 16,
    rangeAttackValue: 16,
    terrainDefense: true,
    originPromotion: [ePromotion.PROMOTION_COUTER_RIDING],
    movement: 2,
    resource: eUnitResource.UNIT_RESOURCE_NONE,
    startTechnology: eTechnology.TECH_CIVIL_SERVICE,
    endTechnology: eTechnology.TECH_RIFLING,
    iconSrc: "UNIT_ZULU_IMPI.png",
  },
  {
    id: eUnit.UNIT_MUSKETMAN,
    name: "火枪兵",
    era: eEra.ERA_RENAISSANCE,
    type: eUnitType.UNIT_TYPE_WEAPON,
    nationality: eNationality.NATION_NONE,
    substitution: eUnit.UNIT_NONE,
    upgrade: eUnit.UNIT_NONE,
    cost: 150,
    closeCombat: true,
    attackRange: 1,
    attackValue: 24,
    rangeAttackValue: 24,
    terrainDefense: true,
    originPromotion: [],
    movement: 2,
    resource: eUnitResource.UNIT_RESOURCE_NONE,
    startTechnology: eTechnology.TECH_GUNPOWDER,
    endTechnology: eTechnology.TECH_RIFLING,
    iconSrc: "UNIT_MUSKETMAN.png",
  },
  {
    id: eUnit.UNIT_SPANISH_TERCIO,
    name: "方阵士兵",
    era: eEra.ERA_RENAISSANCE,
    type: eUnitType.UNIT_TYPE_CLOSECOMBAT,
    nationality: eNationality.NATION_SPAIN,
    substitution: eUnit.UNIT_MUSKETMAN,
    upgrade: eUnit.UNIT_NONE,
    cost: 160,
    closeCombat: true,
    attackRange: 1,
    attackValue: 26,
    rangeAttackValue: 26,
    terrainDefense: true,
    originPromotion: [ePromotion.PROMOTION_COUTER_RIDING],
    movement: 2,
    resource: eUnitResource.UNIT_RESOURCE_NONE,
    startTechnology: eTechnology.TECH_GUNPOWDER,
    endTechnology: eTechnology.TECH_RIFLING,
    iconSrc: "UNIT_SPANISH_TERCIO.png",
  },
  {
    id: eUnit.UNIT_FRENCH_MUSKETEER,
    name: "法国火枪兵",
    era: eEra.ERA_RENAISSANCE,
    type: eUnitType.UNIT_TYPE_WEAPON,
    nationality: eNationality.NATION_FRANCE,
    substitution: eUnit.UNIT_MUSKETMAN,
    upgrade: eUnit.UNIT_NONE,
    cost: 150,
    closeCombat: true,
    attackRange: 1,
    attackValue: 28,
    rangeAttackValue: 28,
    terrainDefense: true,
    originPromotion: [],
    movement: 2,
    resource: eUnitResource.UNIT_RESOURCE_NONE,
    startTechnology: eTechnology.TECH_GUNPOWDER,
    endTechnology: eTechnology.TECH_RIFLING,
    iconSrc: "UNIT_FRENCH_MUSKETEER.png",
  },
  {
    id: eUnit.UNIT_AMERICAN_MINUTEMAN,
    name: "快速民兵",
    era: eEra.ERA_RENAISSANCE,
    type: eUnitType.UNIT_TYPE_WEAPON,
    nationality: eNationality.NATION_AMERICA,
    substitution: eUnit.UNIT_MUSKETMAN,
    upgrade: eUnit.UNIT_NONE,
    cost: 150,
    closeCombat: true,
    attackRange: 1,
    attackValue: 24,
    rangeAttackValue: 24,
    terrainDefense: true,
    originPromotion: [ePromotion.PROMOTION_DRILL_I],
    movement: 2,
    resource: eUnitResource.UNIT_RESOURCE_NONE,
    startTechnology: eTechnology.TECH_GUNPOWDER,
    endTechnology: eTechnology.TECH_RIFLING,
    iconSrc: "UNIT_AMERICAN_MINUTEMAN.png",
  },
  {
    id: eUnit.UNIT_OTTOMAN_JANISSARY,
    name: "苏丹亲兵",
    era: eEra.ERA_RENAISSANCE,
    type: eUnitType.UNIT_TYPE_WEAPON,
    nationality: eNationality.NATION_OSMAN,
    substitution: eUnit.UNIT_MUSKETMAN,
    upgrade: eUnit.UNIT_NONE,
    cost: 150,
    closeCombat: true,
    attackRange: 1,
    attackValue: 24,
    rangeAttackValue: 24,
    terrainDefense: true,
    originPromotion: [ePromotion.PROMOTION_COUNTER_CITY_20],
    movement: 2,
    resource: eUnitResource.UNIT_RESOURCE_NONE,
    startTechnology: eTechnology.TECH_GUNPOWDER,
    endTechnology: eTechnology.TECH_RIFLING,
    iconSrc: "UNIT_OTTOMAN_JANISSARY.png",
  },
  {
    id: eUnit.UNIT_CANNON,
    name: "加农炮",
    era: eEra.ERA_RENAISSANCE,
    type: eUnitType.UNIT_TYPE_SIEGE,
    nationality: eNationality.NATION_NONE,
    substitution: eUnit.UNIT_NONE,
    upgrade: eUnit.UNIT_NONE,
    cost: 185,
    closeCombat: false,
    attackRange: 2,
    attackValue: 14,
    rangeAttackValue: 20,
    terrainDefense: false,
    originPromotion: [ePromotion.PROMOTION_COUNTER_CITY_200],
    movement: 2,
    resource: eUnitResource.UNIT_RESOURCE_NONE,
    startTechnology: eTechnology.TECH_CHEMISTRY,
    endTechnology: eTechnology.TECH_DYNAMITE,
    iconSrc: "UNIT_CANNON.png",
  },
  {
    id: eUnit.UNIT_LANCER,
    name: "枪骑兵",
    era: eEra.ERA_RENAISSANCE,
    type: eUnitType.UNIT_TYPE_RIDING,
    nationality: eNationality.NATION_NONE,
    substitution: eUnit.UNIT_NONE,
    upgrade: eUnit.UNIT_NONE,
    cost: 185,
    closeCombat: true,
    attackRange: 1,
    attackValue: 25,
    rangeAttackValue: 25,
    terrainDefense: false,
    originPromotion: [
      ePromotion.PROMOTION_DEBUFF_CITY_33,
      ePromotion.PROMOTION_FORMATION_I,
    ],
    movement: 4,
    resource: eUnitResource.UNIT_RESOURCE_HORSE,
    startTechnology: eTechnology.TECH_METALLURGY,
    endTechnology: eTechnology.TECH_COMBINED_ARMS,
    iconSrc: "UNIT_LANCER.png",
  },
  {
    id: eUnit.UNIT_POLISH_WINGED_HUSSAR,
    name: "翼骑兵",
    era: eEra.ERA_RENAISSANCE,
    type: eUnitType.UNIT_TYPE_RIDING,
    nationality: eNationality.NATION_POLAND,
    substitution: eUnit.UNIT_LANCER,
    upgrade: eUnit.UNIT_NONE,
    cost: 185,
    closeCombat: true,
    attackRange: 1,
    attackValue: 28,
    rangeAttackValue: 28,
    terrainDefense: false,
    originPromotion: [
      ePromotion.PROMOTION_DEBUFF_CITY_33,
      ePromotion.PROMOTION_FORMATION_I,
      ePromotion.PROMOTION_SHOCK_I,
    ],
    movement: 5,
    resource: eUnitResource.UNIT_RESOURCE_HORSE,
    startTechnology: eTechnology.TECH_METALLURGY,
    endTechnology: eTechnology.TECH_COMBINED_ARMS,
    iconSrc: "UNIT_POLISH_WINGED_HUSSAR.png",
  },
  {
    id: eUnit.UNIT_SWEDISH_HAKKAPELIITTA,
    name: "北境轻骑兵",
    era: eEra.ERA_RENAISSANCE,
    type: eUnitType.UNIT_TYPE_RIDING,
    nationality: eNationality.NATION_SWEDEN,
    substitution: eUnit.UNIT_LANCER,
    upgrade: eUnit.UNIT_NONE,
    cost: 185,
    closeCombat: true,
    attackRange: 1,
    attackValue: 25,
    rangeAttackValue: 25,
    terrainDefense: false,
    originPromotion: [
      ePromotion.PROMOTION_DEBUFF_CITY_33,
      ePromotion.PROMOTION_FORMATION_I,
    ],
    movement: 4,
    resource: eUnitResource.UNIT_RESOURCE_HORSE,
    startTechnology: eTechnology.TECH_METALLURGY,
    endTechnology: eTechnology.TECH_COMBINED_ARMS,
    iconSrc: "UNIT_SWEDISH_HAKKAPELIITTA.png",
  },
  {
    id: eUnit.UNIT_OTTOMAN_SIPAHI,
    name: "西帕尔骑兵",
    era: eEra.ERA_RENAISSANCE,
    type: eUnitType.UNIT_TYPE_RIDING,
    nationality: eNationality.NATION_OSMAN,
    substitution: eUnit.UNIT_LANCER,
    upgrade: eUnit.UNIT_NONE,
    cost: 185,
    closeCombat: true,
    attackRange: 1,
    attackValue: 25,
    rangeAttackValue: 25,
    terrainDefense: false,
    originPromotion: [
      ePromotion.PROMOTION_DEBUFF_CITY_33,
      ePromotion.PROMOTION_FORMATION_I,
    ],
    movement: 5,
    resource: eUnitResource.UNIT_RESOURCE_HORSE,
    startTechnology: eTechnology.TECH_METALLURGY,
    endTechnology: eTechnology.TECH_COMBINED_ARMS,
    iconSrc: "UNIT_OTTOMAN_SIPAHI.png",
  },
  {
    id: eUnit.UNIT_CARAVEL,
    name: "轻帆",
    era: eEra.ERA_RENAISSANCE,
    type: eUnitType.UNIT_TYPE_SEACLOSECOMBAT,
    nationality: eNationality.NATION_NONE,
    substitution: eUnit.UNIT_NONE,
    upgrade: eUnit.UNIT_NONE,
    cost: 120,
    closeCombat: true,
    attackRange: 1,
    attackValue: 20,
    rangeAttackValue: 20,
    terrainDefense: true,
    originPromotion: [],
    movement: 4,
    resource: eUnitResource.UNIT_RESOURCE_NONE,
    startTechnology: eTechnology.TECH_ASTRONOMY,
    endTechnology: eTechnology.TECH_STEAM_POWER,
    iconSrc: "UNIT_CARAVEL.png",
  },
  {
    id: eUnit.UNIT_PORTUGUESE_NAU,
    name: "克拉克帆船",
    era: eEra.ERA_RENAISSANCE,
    type: eUnitType.UNIT_TYPE_SEACLOSECOMBAT,
    nationality: eNationality.NATION_PORTUGAL,
    substitution: eUnit.UNIT_CARAVEL,
    upgrade: eUnit.UNIT_NONE,
    cost: 120,
    closeCombat: true,
    attackRange: 1,
    attackValue: 20,
    rangeAttackValue: 20,
    terrainDefense: true,
    originPromotion: [],
    movement: 4,
    resource: eUnitResource.UNIT_RESOURCE_NONE,
    startTechnology: eTechnology.TECH_ASTRONOMY,
    endTechnology: eTechnology.TECH_STEAM_POWER,
    iconSrc: "UNIT_PORTUGUESE_NAU.png",
  },
  {
    id: eUnit.UNIT_KOREAN_TURTLE_SHIP,
    name: "龟船",
    era: eEra.ERA_RENAISSANCE,
    type: eUnitType.UNIT_TYPE_SEACLOSECOMBAT,
    nationality: eNationality.NATION_KOREA,
    substitution: eUnit.UNIT_CARAVEL,
    upgrade: eUnit.UNIT_NONE,
    cost: 120,
    closeCombat: true,
    attackRange: 1,
    attackValue: 36,
    rangeAttackValue: 36,
    terrainDefense: true,
    originPromotion: [],
    movement: 4,
    resource: eUnitResource.UNIT_RESOURCE_NONE,
    startTechnology: eTechnology.TECH_ASTRONOMY,
    endTechnology: eTechnology.TECH_REPLACEABLE_PARTS,
    iconSrc: "UNIT_KOREAN_TURTLE_SHIP.png",
  },
  {
    id: eUnit.UNIT_PRIVATEER,
    name: "私掠舰",
    era: eEra.ERA_RENAISSANCE,
    type: eUnitType.UNIT_TYPE_SEACLOSECOMBAT,
    nationality: eNationality.NATION_NONE,
    substitution: eUnit.UNIT_NONE,
    upgrade: eUnit.UNIT_NONE,
    cost: 150,
    closeCombat: true,
    attackRange: 1,
    attackValue: 25,
    rangeAttackValue: 25,
    terrainDefense: true,
    originPromotion: [ePromotion.PROMOTION_HITCOAST_I],
    movement: 5,
    resource: eUnitResource.UNIT_RESOURCE_NONE,
    startTechnology: eTechnology.TECH_NAVIGATION,
    endTechnology: eTechnology.TECH_COMBUSTION,
    iconSrc: "UNIT_PRIVATEER.png",
  },
  {
    id: eUnit.UNIT_DUTCH_SEA_BEGGAR,
    name: "海上乞丐",
    era: eEra.ERA_RENAISSANCE,
    type: eUnitType.UNIT_TYPE_SEACLOSECOMBAT,
    nationality: eNationality.NATION_NETHERLANDS,
    substitution: eUnit.UNIT_PRIVATEER,
    upgrade: eUnit.UNIT_NONE,
    cost: 150,
    closeCombat: true,
    attackRange: 1,
    attackValue: 25,
    rangeAttackValue: 25,
    terrainDefense: true,
    originPromotion: [
      ePromotion.PROMOTION_HITCOAST_I,
      ePromotion.PROMOTION_HITCOAST_II,
    ],
    movement: 5,
    resource: eUnitResource.UNIT_RESOURCE_NONE,
    startTechnology: eTechnology.TECH_NAVIGATION,
    endTechnology: eTechnology.TECH_COMBUSTION,
    iconSrc: "UNIT_DUTCH_SEA_BEGGAR.png",
  },
  {
    id: eUnit.UNIT_FRIGATE,
    name: "巡防舰",
    era: eEra.ERA_RENAISSANCE,
    type: eUnitType.UNIT_TYPE_SEAREMOTE,
    nationality: eNationality.NATION_NONE,
    substitution: eUnit.UNIT_NONE,
    upgrade: eUnit.UNIT_NONE,
    cost: 185,
    closeCombat: false,
    attackRange: 2,
    attackValue: 25,
    rangeAttackValue: 28,
    terrainDefense: true,
    originPromotion: [],
    movement: 5,
    resource: eUnitResource.UNIT_RESOURCE_IRON,
    startTechnology: eTechnology.TECH_NAVIGATION,
    endTechnology: eTechnology.TECH_ELECTRONICS,
    iconSrc: "UNIT_FRIGATE.png",
  },
  {
    id: eUnit.UNIT_ENGLISH_SHIPOFTHELINE,
    name: "风帆战舰",
    era: eEra.ERA_RENAISSANCE,
    type: eUnitType.UNIT_TYPE_SEAREMOTE,
    nationality: eNationality.NATION_ENGLAND,
    substitution: eUnit.UNIT_FRIGATE,
    upgrade: eUnit.UNIT_NONE,
    cost: 170,
    closeCombat: false,
    attackRange: 2,
    attackValue: 30,
    rangeAttackValue: 35,
    terrainDefense: true,
    originPromotion: [],
    movement: 5,
    resource: eUnitResource.UNIT_RESOURCE_IRON,
    startTechnology: eTechnology.TECH_NAVIGATION,
    endTechnology: eTechnology.TECH_ELECTRONICS,
    iconSrc: "UNIT_ENGLISH_SHIPOFTHELINE.png",
  },
  {
    id: eUnit.UNIT_ARTILLERY,
    name: "火炮",
    era: eEra.ERA_INDUSTRIAL,
    type: eUnitType.UNIT_TYPE_SIEGE,
    nationality: eNationality.NATION_NONE,
    substitution: eUnit.UNIT_NONE,
    upgrade: eUnit.UNIT_NONE,
    cost: 250,
    closeCombat: false,
    attackRange: 3,
    attackValue: 21,
    rangeAttackValue: 28,
    terrainDefense: false,
    originPromotion: [ePromotion.PROMOTION_COUNTER_CITY_200],
    movement: 2,
    resource: eUnitResource.UNIT_RESOURCE_NONE,
    startTechnology: eTechnology.TECH_DYNAMITE,
    endTechnology: eTechnology.TECH_FUTURE_TECH,
    iconSrc: "UNIT_ARTILLERY.png",
  },
  {
    id: eUnit.UNIT_GATLINGGUN,
    name: "加特林机枪",
    era: eEra.ERA_INDUSTRIAL,
    type: eUnitType.UNIT_TYPE_REMOTE,
    nationality: eNationality.NATION_NONE,
    substitution: eUnit.UNIT_NONE,
    upgrade: eUnit.UNIT_NONE,
    cost: 225,
    closeCombat: false,
    attackRange: 1,
    attackValue: 30,
    rangeAttackValue: 30,
    terrainDefense: true,
    originPromotion: [],
    movement: 2,
    resource: eUnitResource.UNIT_RESOURCE_NONE,
    startTechnology: eTechnology.TECH_INDUSTRIALIZATION,
    endTechnology: eTechnology.TECH_BALLISTICS,
    iconSrc: "UNIT_GATLINGGUN.png",
  },
  {
    id: eUnit.UNIT_RIFLEMAN,
    name: "来复枪兵",
    era: eEra.ERA_INDUSTRIAL,
    type: eUnitType.UNIT_TYPE_WEAPON,
    nationality: eNationality.NATION_NONE,
    substitution: eUnit.UNIT_NONE,
    upgrade: eUnit.UNIT_NONE,
    cost: 225,
    closeCombat: true,
    attackRange: 1,
    attackValue: 34,
    rangeAttackValue: 34,
    terrainDefense: true,
    originPromotion: [],
    movement: 2,
    resource: eUnitResource.UNIT_RESOURCE_NONE,
    startTechnology: eTechnology.TECH_RIFLING,
    endTechnology: eTechnology.TECH_REPLACEABLE_PARTS,
    iconSrc: "UNIT_RIFLEMAN.png",
  },
  {
    id: eUnit.UNIT_SWEDISH_CAROLEAN,
    name: "卡尔远征军",
    era: eEra.ERA_INDUSTRIAL,
    type: eUnitType.UNIT_TYPE_WEAPON,
    nationality: eNationality.NATION_SWEDEN,
    substitution: eUnit.UNIT_RIFLEMAN,
    upgrade: eUnit.UNIT_NONE,
    cost: 225,
    closeCombat: true,
    attackRange: 1,
    attackValue: 34,
    rangeAttackValue: 34,
    terrainDefense: true,
    originPromotion: [],
    movement: 2,
    resource: eUnitResource.UNIT_RESOURCE_NONE,
    startTechnology: eTechnology.TECH_RIFLING,
    endTechnology: eTechnology.TECH_REPLACEABLE_PARTS,
    iconSrc: "UNIT_SWEDISH_CAROLEAN.png",
  },
  {
    id: eUnit.UNIT_ETHIOPIAN_MEHAL_SEFARI,
    name: "帝国卫队",
    era: eEra.ERA_INDUSTRIAL,
    type: eUnitType.UNIT_TYPE_WEAPON,
    nationality: eNationality.NATION_ETHIOPIA,
    substitution: eUnit.UNIT_RIFLEMAN,
    upgrade: eUnit.UNIT_NONE,
    cost: 200,
    closeCombat: true,
    attackRange: 1,
    attackValue: 34,
    rangeAttackValue: 34,
    terrainDefense: true,
    originPromotion: [ePromotion.PROMOTION_DRILL_I],
    movement: 2,
    resource: eUnitResource.UNIT_RESOURCE_NONE,
    startTechnology: eTechnology.TECH_RIFLING,
    endTechnology: eTechnology.TECH_REPLACEABLE_PARTS,
    iconSrc: "UNIT_ETHIOPIAN_MEHAL_SEFARI.png",
  },
  {
    id: eUnit.UNIT_DANISH_SKI_INFANTRY,
    name: "雪橇步兵",
    era: eEra.ERA_INDUSTRIAL,
    type: eUnitType.UNIT_TYPE_WEAPON,
    nationality: eNationality.NATION_DENMARK,
    substitution: eUnit.UNIT_RIFLEMAN,
    upgrade: eUnit.UNIT_NONE,
    cost: 225,
    closeCombat: true,
    attackRange: 1,
    attackValue: 34,
    rangeAttackValue: 34,
    terrainDefense: true,
    originPromotion: [ePromotion.PROMOTION_POLOA_PIONEER],
    movement: 2,
    resource: eUnitResource.UNIT_RESOURCE_NONE,
    startTechnology: eTechnology.TECH_RIFLING,
    endTechnology: eTechnology.TECH_REPLACEABLE_PARTS,
    iconSrc: "UNIT_DANISH_SKI_INFANTRY.png",
  },
  {
    id: eUnit.UNIT_CAVALRY,
    name: "骑兵",
    era: eEra.ERA_INDUSTRIAL,
    type: eUnitType.UNIT_TYPE_RIDING,
    nationality: eNationality.NATION_NONE,
    substitution: eUnit.UNIT_NONE,
    upgrade: eUnit.UNIT_NONE,
    cost: 225,
    closeCombat: true,
    attackRange: 1,
    attackValue: 34,
    rangeAttackValue: 34,
    terrainDefense: false,
    originPromotion: [ePromotion.PROMOTION_DEBUFF_CITY_33],
    movement: 4,
    resource: eUnitResource.UNIT_RESOURCE_HORSE,
    startTechnology: eTechnology.TECH_MILITARY_SCIENCE,
    endTechnology: eTechnology.TECH_COMBUSTION,
    iconSrc: "UNIT_CAVALRY.png",
  },
  {
    id: eUnit.UNIT_BERBER_CAVALRY,
    name: "柏柏尔骑兵", //TODO:
    era: eEra.ERA_INDUSTRIAL,
    type: eUnitType.UNIT_TYPE_RIDING,
    nationality: eNationality.NATION_MOROCCO,
    substitution: eUnit.UNIT_CAVALRY,
    upgrade: eUnit.UNIT_NONE,
    cost: 225,
    closeCombat: true,
    attackRange: 1,
    attackValue: 34,
    rangeAttackValue: 34,
    terrainDefense: false,
    originPromotion: [ePromotion.PROMOTION_DEBUFF_CITY_33],
    movement: 4,
    resource: eUnitResource.UNIT_RESOURCE_HORSE,
    startTechnology: eTechnology.TECH_MILITARY_SCIENCE,
    endTechnology: eTechnology.TECH_COMBUSTION,
    iconSrc: "UNIT_BERBER_CAVALRY.png",
  },
  {
    id: eUnit.UNIT_SHOSHONE_COMANCHE_RIDERS,
    name: "科曼奇骑兵",
    era: eEra.ERA_INDUSTRIAL,
    type: eUnitType.UNIT_TYPE_RIDING,
    nationality: eNationality.NATION_SHOSHONE,
    substitution: eUnit.UNIT_CAVALRY,
    upgrade: eUnit.UNIT_NONE,
    cost: 200,
    closeCombat: true,
    attackRange: 1,
    attackValue: 34,
    rangeAttackValue: 34,
    terrainDefense: false,
    originPromotion: [ePromotion.PROMOTION_DEBUFF_CITY_33],
    movement: 4,
    resource: eUnitResource.UNIT_RESOURCE_HORSE,
    startTechnology: eTechnology.TECH_MILITARY_SCIENCE,
    endTechnology: eTechnology.TECH_COMBUSTION,
    iconSrc: "UNIT_BERBER_CAVALRY.png",
  },
  {
    id: eUnit.UNIT_RUSSIAN_COSSACK,
    name: "哥萨克骑兵",
    era: eEra.ERA_INDUSTRIAL,
    type: eUnitType.UNIT_TYPE_RIDING,
    nationality: eNationality.NATION_RUSSIA,
    substitution: eUnit.UNIT_CAVALRY,
    upgrade: eUnit.UNIT_NONE,
    cost: 225,
    closeCombat: true,
    attackRange: 1,
    attackValue: 34,
    rangeAttackValue: 34,
    terrainDefense: false,
    originPromotion: [
      ePromotion.PROMOTION_DEBUFF_CITY_33,
      ePromotion.PROMOTION_RUSSIA_BLADE, //TODO:
    ],
    movement: 4,
    resource: eUnitResource.UNIT_RESOURCE_HORSE,
    startTechnology: eTechnology.TECH_MILITARY_SCIENCE,
    endTechnology: eTechnology.TECH_COMBUSTION,
    iconSrc: "UNIT_BERBER_CAVALRY.png",
  },
];
